name: Coverage process

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - id: spotless
      run: mvn spotless:check animal-sniffer:check test verify
    # - if: failure()
    #   name: Test Spotless Failed
      # run: |
      #   wget https://raw.githubusercontent.com/segmentio/circleci-notifications/master/slack-notify-branch.sh
      #   chmod u+x slack-notify-branch.sh
      #   BUILD_STATUS="Failed" NOTIFY_BRANCH="master" ./slack-notify-branch.sh
    - if: steps.spotless.conclusion == 'success'
      run: mvn -B package

    - name: Run command cobertura
      run: mvn cobertura:cobertura
    - run: bash <(curl -s https://codecov.io/bash)